version: "3.9"

services:
  postgres:
    image: postgres
    container_name: leetcode_build
    environment:
      POSTGRES_DB: leetcode
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPassword123
    ports:
      - "5432:5432"
    volumes:
      - leetcode_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  leetcode_db_data: